services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped

  caddy:
    image: ghcr.io/pavelsamodurov/caddy-cloudflare:latest
    ports:
      - "80:80"
      - "8443:443"
      - "8443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    restart: unless-stopped

volumes:
  uptime-kuma-data:
  caddy-data:
  caddy-config:
