apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-gateway.fullname" . }}-config
  labels:
    {{- include "ai-gateway.labels" . | nindent 4 }}
data:
  application-env.yaml: |
    {{- .Values.applicationConfig | nindent 4 }}