apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-gateway.fullname" . }}-secrets
  labels:
    {{- include "ai-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  DEEPSEEK_API_KEY: {{ .Values.deepseekApiKey | quote }}
  GROQ_API_KEY: {{ .Values.groqApiKey | quote }}
  DEEPINFRA_API_KEY: {{ .Values.deepinfraApiKey | quote }}
  POSTGRES_USER: {{ .Values.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | quote }}
  STT_MAX_TOKEN: {{ .Values.sttMaxToken | quote }}
